app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

homepage:
    path: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/index.html.twig
        _locale:     '%locale%'

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
